
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T18:29:39-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "a91a257d2c8687a7931721d387b2ffeb6aa71fc2",
 "version": "0.36.2+1.ga91a257.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
